name: CakeDay
version: '${version}'
main: dev.nedhuman.cakeday.CakeDay
api-version: '1.20'
author: NedHuman
description: Plugin which gives you rewards if you join on your cake day
commands:
  receivedcake:
    description: Years when you received cake
  whenismycakeday:
    description: When is my cake day?
